#DECLARACION DE VARIABLES

nombre = 'Larry'    # TIPO DE DATO STRING
edad = 21   # TIPO DE DATO INT
sueldo = 400.35 # TIPO DE DATO SUELDO
casado = False  # TIPO DE DATO BOOLEANO

print(nombre)   #IMPRESION DEL CONTENIDO DE LA VARIABLE NOMBRE
print(edad) #IMPRESION DEL CONTENIDO DE LA VARIABLE EDAD
print(sueldo)   #IMPRESION DEL CONTENIDO DE LA VARIABLE SUELDA
print(casado)   #IMPRESION DEL CONTENIDO DE LA VARIABLE CASADO


# SOLICITUD DE DATOS POR TECLADO

nombre = input('INGRESE SU NUEVO NOMBRE: ') #SOLICITUD DE DATOS PARA ALMACENARLOS EN LA VARIABLE NOMBRE

print(nombre)   #IMPRESION DEL CONTENIDO DE LA VARIABLE NOMBRE


# OPERACIONES ARITMETICAS

numero1 = 0 #DECLARACION DE UNA VARIABLE TIPO INT
numero2 = 0 #DECLARACION DE UNA VARIABLE TIPO INT
resultado = 0 #DECLARACION DE UNA VARIABLE TIPO INT

numero1 = eval(input('INGRESE UN NUMERO: '))
numero2 = eval(input('INGRESE OTRO NUMERO: '))

resultado = numero1 + numero2   # SE REALIZA UNA OPERACION ARITMETICA Y EL RESULTADO SE GUARDA EN LA VARIABLE RESULTADO 

print(resultado)    #IMPRIME EL CONTENIDO DE LA VARIABLE RESULTADO 


'''
OPERADORES ARITMETICOS
+ SUMA
- RESTA
* MULTIPLICACION
/ DIVISION
// DIVISION ENTERA
%  MODULO
** POTENCIA
'''

#CADENAS DE TEXTO

print('HOLA ' * 100)    #IMPRIME LA PALABRA HOLA 100 VECES

print('''
*********************************************
*        FORMATO EN CADENAS DE TEXTO        *
*********************************************
''')    #LE DAMOS FORMATO A UNA CADENA DE TEXTO Y LUEGO LA IMPRIMIMOS

print('NOMBRE: ' + nombre)  #CONCATENACION DE CADENAS DE TEXTO

#TUPLAS
tupla = (1,2,3,4,5,6,7) #DECLARACION DE UNA TUPLA

print(tupla[0]) #PARA ACCEDER A LOS VALORES UTILIZAMOS LOS INDICES QUE VAN DESDE EL CERO
print(tupla[1:])    #ESTA SENTENCIA NOS PERMITIRA MOSTRAR LOS VALORES DESDE EL INDICE 1 HASTA EL ULTIMO
print(tupla[:]) #ESTA SENTENCIA NOS PERMITE IMPRIMIR TODOS LOS VALORES
print(tupla[::2])   #ESTA SENTENCIA MOSTRARA TODOS LOS VALORES CADA DOS VALORES

#LAS TUPLAS UTILIZAN PARENTESIS, Y PARA SEPARAR SUS ELEMENTOS SE HACE MEDIANTE UNA COMA
#LAS TUPLAS NO PUEDEN CAMBIAR SUS ELEMENTOS UNA VEZ INICIADO EL PROGRAMA
#LAS TUPLAS PUEDEN GUARDAR CUALQUIER TIPO DE VALOR QUE NO CAMBIE

#LISTAS
lista = ['Larry','Juan','Kathy','Maria']    #DECLARACION DE UNA LISTA

print(lista[0]) #PARA ACCEDER A LOS VALORES UTILIZAMOS LOS INDICES QUE VAN DESDE EL CERO
print(lista[1:])    #ESTA SENTENCIA NOS PERMITIRA MOSTRAR LOS VALORES DESDE EL INDICE 1 HASTA EL ULTIMO
print(lista[:]) #ESTA SENTENCIA NOS PERMITE IMPRIMIR TODOS LOS VALORES
print(lista[::2])   #ESTA SENTENCIA MOSTRARA TODOS LOS VALORES CADA DOS VALORES

#LAS LISTAS UTILIZAN CORCHETES, Y PARA SEPARAR SUS ELEMENTOS SE HACE MEDIANTE UNA COMA
#LAS LISTAS PERMITEN CAMBIAR SUS ELEMENTOS UNA VEZ INICIA EL PROGRAMA
#LAS LISTAS PUEDEN ALMACENAR CUALQUIER TIPO DE VALOR

#DICCIONARIOS
diccionario = {'clave1':'valor1', 'clave2':'valor2', 'clave3':'valor3'}   #DECLARACION DE UN DICCIONARIO


print(diccionario['clave1'])    #PARA ACCEDER A UN VALOR DEL DICCIONARIO DEBEMOS UTILIZAR SU CLAVE 

#LOS DICCIONARIOS UTILIZAN LLAVES, PARA RELACIONAR DOS VALORES SE UTILIZAN LOS DOS PUNTOS
# Y PARA SEPARAR LOS ELEMENTOS SE UTILIZAN LAS COMAS
#LOS DICCIONARIOS PUEDEN GUARDAR CUALQUEIR TIPO DE DATOS
#LOS DICCIONARIOS UTILIZAN UNA CLAVE QUE PERMITIRA ACCEDER AL VALOR


